#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

    import sys

    #use c99
    ctx.env.append_value('CFLAGS', ['-std=c99'])

    # Only thing we need is noroi_base
    ctx.env.append_value('NOROI_CLIENT_LIB', ['noroi_base']);

def build(ctx):
    ctx.install_files('${PREFIX}/include/noroi/client', ctx.path.ant_glob('include/noroi/client/**/*.h'))

    ctx.shlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='noroi_client',
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.NOROI_CLIENT_LIB)
