#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

    import sys

    #use c99
    ctx.env.append_value('CFLAGS', ['-std=c99'])

    # For interthread communication
    ctx.check_cc(lib='zmq', uselib_store='zmq', mandatory=True)
    ctx.env.append_value('NOROI_BASE_LIB', ['zmq'])

    # This is needed for glfw!
    if sys.platform == 'linux':
        ctx.check_cc(lib='pthread', uselib_store='pthread', mandatory=True)
        ctx.env.append_value('NOROI_BASE_LIB', ['pthread']);

        ctx.check_cc(lib='m', uselib_store='m', mandatory=True)
        ctx.env.append_value('NOROI_BASE_LIB', ['m']);

        ctx.check_cc(lib='dl', uselib_store='dl', mandatory=True)
        ctx.env.append_value('NOROI_BASE_LIB', ['dl'])

    if sys.platform == 'win32' or sys.platform == 'cygwin' or sys.platform == 'msys':
        ctx.check_cc(lib='gdi32', uselib_store='gdi32', mandatory=True)
        ctx.env.append_value('NOROI_BASE_LIB', ['gdi32'])

def build(ctx):
    ctx.install_files('${PREFIX}/include/noroi/base', ctx.path.ant_glob('include/noroi/base/**/*.h*'))

    ctx.shlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='noroi_base',
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.NOROI_BASE_LIB)
