#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')
    ctx.add_option('--impl', action='store', default='terminal', help='Choose the implementation')

def configure(ctx):
    ctx.load('compiler_c')

    import sys

    if ctx.options.impl == 'gl':
        ctx.env.append_value('NOROI_LIB', ['glad'])

        ctx.check_cxx(lib='glfw', uselib_store='glfw', mandatory=True)
        ctx.env.append_value('NOROI_LIB', ['glfw'])

        ctx.env.CFLAGS = ['-DNOROI_USE_GLFW']

    elif ctx.options.impl == 'terminal':
        if sys.platform == 'win32' or sys.platform == 'cygwin' or sys.platform == 'msys':
            ctx.env.CFLAGS = ['-DNOROI_TERMINAL_WINDOWS']
        else:
            ctx.check_cxx(lib='ncurses', uselib_store='ncurses', mandatory=True)
            ctx.env.append_value('NOROI_LIB', ['ncurses'])

            ctx.env.CFLAGS = ['-DNOROI_TERMINAL_NCURSES']

def build(ctx):
    ctx.install_files('${PREFIX}/include', ctx.path.ant_glob('include/noroi/**/*.h'))

    ctx.stlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='noroi',
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.NOROI_LIB)
