#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

    import sys

    #use c99
    ctx.env.append_value('CFLAGS', ['-std=c99'])

    # We need noroi_base
    ctx.env.append_value('NOROI_GLFW_SERVER_LIB', ['noroi_base'])

    # For our window + opengl context.
    ctx.check_cfg(package='glfw3', args='--cflags --libs', uselib_store='glfw', mandatory=True)
    ctx.env.append_value('NOROI_GLFW_SERVER_LIB', ['glfw'])

    # For text rendering
    ctx.check_cfg(package='freetype2', args='--cflags --libs', uselib_store='freetype', mandatory=True);
    ctx.env.append_value('NOROI_GLFW_SERVER_LIB', ['freetype']);

def build(ctx):
    ctx.install_files('${PREFIX}/include/noroi/glfw_server', ctx.path.ant_glob('include/noroi/glfw_server/**/*.h'))

    ctx.shlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='noroi_glfw_server',
              includes=['include'],
              export_includes=['include'],
              use=ctx.env.NOROI_GLFW_SERVER_LIB)
