#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')

def build(ctx):
    ctx.stlib(source=ctx.path.ant_glob('src/**/*.c'),
              target='unity',
              includes=['include'],
              export_includes=['include'])
