#! /usr/bin/env python
# encoding: utf-8

def options(ctx):
    ctx.add_option('--buildtestserver', action='store', default=True, help='Build the test server also.')

def configure(ctx):
    if ctx.options.buildtestserver:
        ctx.env.BUILD_TEST_SERVER = True
    else:
        ctx.env.BUILD_TEST_SERVER = False

def build(ctx):
    if ctx.env.BUILD_TEST_SERVER:
        # Copy over everything in our data folder.
        for file in ctx.path.ant_glob('data/**/*'):
            ctx(feature='subst', name='data_' + file.name, rule='cp ${SRC} ${TGT}', source=file, target=file.get_bld())

        ctx.install_files('${PREFIX}/share/noroi_test_server', ctx.path.ant_glob('data/*.*'))

        ctx.program(source=ctx.path.ant_glob('src/**/*.c'),
                    target='noroi_test_server',
                    includes=['include'],
                    use='noroi_glfw_server',
                    vnum='0.1')
